version: '3.8'

services:
  declarant-api-gateway:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_URL_SEC=${DATABASE_URL_SEC}
      - DATABASE_URL_MASTER=${DATABASE_URL_MASTER}
    depends_on:
      - master-service
      - sec-service

  master-service:
    image: master-service:latest
    build:
      context: .
      dockerfile: Dockerfile.master
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_URL_SEC=${DATABASE_URL_SEC}
      - DATABASE_URL_MASTER=${DATABASE_URL_MASTER}


  master-service:
    image: sec-service:latest
    build:
      context: .
      dockerfile: Dockerfile.sec
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_URL_SEC=${DATABASE_URL_SEC}
      - DATABASE_URL_MASTER=${DATABASE_URL_MASTER}

networks:
  app-network:
    driver: bridge
